### ISSUE TITLE
Update Repository Description

### ISSUE THREAD

**Issue by wbond** [MarkMichos/FireCode-color-scheme#1]
The description of this repo says it only work with Sublime Text 2, but the package info indicates it works with ST3 also.

**Comment by MarkMichos** [comment]
Oh, well, it works fine on ST3, too

**Comment by wbond** [comment]
So can you just update the repository description to say "Sublime Text" instead of "Sublime Text 2"?

**Comment by MarkMichos** [comment]
Yes, sure.

Where are the stats gone on package control?

**Comment by wbond** [comment]
Hmm, looks like an issue with the renaming, I've got another related issue to look at. They'll be back soon.

**Comment by wbond** [comment]
This should be resolved now (minus the first seen date) https://sublime.wbond.net/packages/FireCode%20Color%20Scheme.
